election/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("vote/", include("vote.urls")),
]

vote/urls.py
from django.urls import URLPattern, path

from . import views
app_name = "sondage"
urlpatterns = [
     
    path("", views.index, name="index"),
    path("<int:question_id>/", views.detail, name="detail"),
    path("<int:question_id>/results/", views.results, name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

vote/models.py
from django.db import models
from django.utils import timezone
import datetime

class Elections(models.Model):
    elections_name = models.CharField(max_length=50)
    publish_date = models.DateTimeField("date de la publication")
    
    def __str__(self):
        return self.elections_name

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    elections = models.ForeignKey(Elections,on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=255)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

class Personnes(models.Model):
    nom = models.CharField(max_length=25)
    prenom = models.CharField(max_length=25)
    login = models.CharField(max_length=50)
    mdp = models.CharField(max_length=50)
    tel = models.CharField(max_length=20)
    date_naissance = models.DateTimeField("date de naissance")

class Coordonnees(models.Model):
    adresse = models.CharField(max_length=50)
    code_postal = models.CharField(max_length=50)
    ville = models.CharField(max_length=50)
    pays = models.CharField(max_length=50)
    personnes = models.ForeignKey(Personnes,on_delete=models.CASCADE)

class Voter(models.Model):
    personnes = models.ForeignKey(Personnes,on_delete=models.CASCADE)
    elections = models.ForeignKey(Elections,on_delete=models.CASCADE)

vote/views.py
 
from django.shortcuts import get_object_or_404, render
 
from django.http import HttpResponse, HttpResponseRedirect
from .models import Elections, Choice
from django.template import loader
from django.urls import reverse

from django.views import generic


def index(request):
   
    latest_question_list = Elections.objects.order_by("-publish_date")[:5]
    context = {"question_list": latest_question_list}
    return render(request, "sondage/index.html", context)


def detail(request, question_id):
     
    question = get_object_or_404(Elections, pk=question_id)
    return render(request, "sondage/detail.html",{"question":question})

def results(request, question_id):
    
    question = get_object_or_404(Elections,pk=question_id)
    return render(request, "sondage/results.html", {"question":question})

def vote(request, question_id):
 
    question = get_object_or_404(Elections, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        return render(request,"sondage/detail.html",{"question":question,"error_message":"Vous devez choisir !!",})
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse("sondage:results", args=(question_id,)))

    
class IndexView(generic.ListView):
    template_name = "sondage/index.html"
    context_object_name = "question_list"

def get_queryset(self):
    return Elections.objects.order_by("-publish_date")[:5]

class DetailView(generic.DetailView):
    model = Elections
    template_name = "sondage/detail.html"

class ResultsView(generic.DetailView):
    model = Elections
    template_name = "sondage/results.html"

vote/templates/sondage/detail.html
<!DOCTYPE html>
<html lang="fr" dir="ltr">

<head>
  <meta charset="utf-8">
  <title></title>
</head>

<body>

  <form action="{% url 'sondage:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
      <legend><h1>{{ question.question_text }}</h1></legend>
      {% if error_message %} <p><strong>{{ error_message }}</strong></p>{% endif %}
      {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id}}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
      {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
    </form>

</body>

</html>

vote/templates/sondage/index.html
<!DOCTYPE html>
{% load static %}
<html lang="fr" dir="ltr">
<head>
  <meta charset="utf-8">
  <title>mon sondage</title>
<link rel="stylesheet" type="text/css" href="{% static 'vote/style.css' %}">
</head>

<body>

  {% if question_list %}
  <ul>
      {% for question in question_list %}
      <li>
          <a href="/vote/{{question.id}}">{{question.elections_name}}</a>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>Pas de sondage disponible.</p>
    {% endif %}

</body>

</html>

vote/templates/sondage/results.html
<h1>{{ question.question_text }}</h1>
<ul>
  {% for choice in question.choice_set.all%}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
  {% endfor %}
</ul>
<a href="{% url 'vote:detail' question.id %}">Voter a nouveau ?</a>